---
# Unusual Flow Duration Response Playbook
name: Unusual Flow Duration Response
description: Playbook for addressing unusual flow duration anomalies

responses:
  - type: tcp_keepalive
    description: Adjust TCP keepalive settings to manage long-lived connections
    commands:
      - ssh {{ src_ip }} "sudo sysctl -w net.ipv4.tcp_keepalive_time=600"
      - ssh {{ src_ip }} "sudo sysctl -w net.ipv4.tcp_keepalive_intvl=60"
      - ssh {{ src_ip }} "sudo sysctl -w net.ipv4.tcp_keepalive_probes=5"
      - ssh {{ src_ip }} "echo success"

  - type: connection_timeout
    description: Apply connection timeouts to prevent overly long connections
    commands:
      - ssh {{ src_ip }} "sudo iptables -A INPUT -p tcp --dport {{ dst_port }} -m conntrack --ctstate ESTABLISHED -m connlimit --connlimit-above 1 -j ACCEPT"
      - ssh {{ src_ip }} "sudo iptables -A INPUT -p tcp --dport {{ dst_port }} -m conntrack --ctstate ESTABLISHED -m conntrack --ctstate NEW -m limit --limit 1/second -j ACCEPT"
      - ssh {{ src_ip }} "sudo iptables -A INPUT -p tcp --dport {{ dst_port }} -m conntrack --ctstate ESTABLISHED -m conntrack --ctstate ESTABLISHED -m timeout --timeout 3600 -j ACCEPT"
      - ssh {{ src_ip }} "echo success"

  - type: idle_connection_management
    description: Configure idle connection management
    commands:
      - ssh {{ src_ip }} "sudo sysctl -w net.ipv4.tcp_fin_timeout=30"
      - ssh {{ src_ip }} "sudo sysctl -w net.netfilter.nf_conntrack_tcp_timeout_established=3600"
      - ssh {{ src_ip }} "sudo sysctl -w net.netfilter.nf_conntrack_tcp_timeout_close_wait=60"
      - ssh {{ src_ip }} "echo success"

  - type: application_timeout
    description: Set application-level timeouts
    commands:
      - ssh {{ src_ip }} "sudo sed -i 's/timeout .*/timeout 600/g' /etc/nginx/nginx.conf"
      - ssh {{ src_ip }} "sudo sed -i 's/keepalive_timeout .*/keepalive_timeout 120;/g' /etc/nginx/nginx.conf"
      - ssh {{ src_ip }} "sudo systemctl restart nginx"
      - ssh {{ src_ip }} "echo success"

  - type: session_management
    description: Implement session management policies
    commands:
      - ssh {{ src_ip }} "sudo iptables -t mangle -A PREROUTING -p tcp -s {{ src_ip }} -d {{ dst_ip }} --dport {{ dst_port }} -m recent --name long_flows --set"
      - ssh {{ src_ip }} "sudo iptables -t mangle -A PREROUTING -p tcp -s {{ src_ip }} -d {{ dst_ip }} --dport {{ dst_port }} -m recent --name long_flows --update --seconds 3600 --hitcount 1 -j MARK --set-mark 1"
      - ssh {{ src_ip }} "sudo tc qdisc add dev eth0 root handle 1: prio"
      - ssh {{ src_ip }} "sudo tc filter add dev eth0 protocol ip parent 1:0 prio 1 handle 1 fw classid 1:1"
      - ssh {{ src_ip }} "echo success"